"""Added some columns

Revision ID: 12569d95ae1b
Revises: 
Create Date: 2023-08-10 15:24:12.873176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '12569d95ae1b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_collections',
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('article_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['article.article_id'], name='article_collections_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], name='article_collections_ibfk_1'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('camp',
    sa.Column('camp_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('city', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('area', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('longitube', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('latitube', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('isService', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('phoneNumber', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('website', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('camp_imageURL', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('camp_imageType', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('camp_imageSize', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('camp_id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('image',
    sa.Column('image_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('article_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('image_sortNumber', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('article_imageURL', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('article_imageType', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('article_imageSize', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['article.article_id'], name='image_ibfk_1'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('user',
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('user_imageURL', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('user_imageType', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('user_imageSize', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('account_createDate', sa.DATE(), nullable=True),
    sa.Column('lastLoginDate', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('follower',
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('follower_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['follower_id'], ['user.user_id'], name='follower_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], name='follower_ibfk_1'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('comment',
    sa.Column('comment_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('article_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('text', mysql.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['article.article_id'], name='comment_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], name='comment_ibfk_2'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('following',
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('following_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['following_id'], ['user.user_id'], name='following_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], name='following_ibfk_1'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('article',
    sa.Column('article_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('article_createDate', mysql.DATETIME(), nullable=True),
    sa.Column('article_title_imageURL', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('article_title_imageType', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('article_title_imageSize', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], name='article_ibfk_1'),
    sa.PrimaryKeyConstraint('article_id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('text',
    sa.Column('text_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('article_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('text_sortNumber', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('content', mysql.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['article.article_id'], name='text_ibfk_1'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
